language: python
python: '3.6'
cache:
  pip: true
services:
- docker
- redis-server
install:
- make deps
script:
- make lint
- git diff --exit-code
- make docker-build
- make docker-login docker-push
